BINS=emuclient
CC=gcc
CFLAGS=-Wall -O2
LIB=-lmingw32 -lSDLmain -lSDL -llibxml2 -lpthread -lws2_32 -liconv
INC=

all: $(BINS)

clean:
	rm -f $(BINS) *~ *.o *.exe

emuclient: emuclient.o sixaxis.o dump.o macros.o config.o conversion.o config_writter.o config_reader.o sdl_tools.o win_serial_con.o calibration.o win_serial_con.o serial_con.o
	$(CC) -o $@ $^ $(LIB)

%.o: %.c
	$(CC) $(CFLAGS) $(INC) -o $@ -c $< 
