include ../../../Makedefs

BINS=windows_test
OBJ=windows_test.o common.o
LIB=../GE.a -lmingw32 -lSDLmain -lSDL -liconv
INC=-I../include #-I/usr/include/ 

all: $(BINS)

clean:
	rm -f $(BINS) *~ *.o

windows_test: $(OBJ)
	$(CC) $(CFLAGS) $(INC) -o $@ $^ $(LIB)

%.o: %.c
	$(CC) $(CFLAGS) $(INC) -o $@ -c $<

