include ../../../Makedefs

BINS=windows_test
OBJ=windows_test.o common.o
LIB=../GE.a -lmingw32 -lSDLmain -lSDL -liconv
INC=-I../include
DEPS=../GE.a

all: $(BINS)

clean:
	rm -f $(BINS) *~ *.o

windows_test: $(OBJ) $(DEPS)
	$(CC) $(CFLAGS) $(INC) -o $@ $(OBJ) $(LIB)

%.o: %.c
	$(CC) $(CFLAGS) $(INC) -o $@ -c $<

